// ═══════════════════════════════════════════════════════════════════════════════
// YI JING & DAOIST QUOTES - For Loading Screen
// ═══════════════════════════════════════════════════════════════════════════════

const YIJING_QUOTES = {
    en: [
        { text: "The superior man understands the signs of heaven and knows the causes of events.", source: "I Ching, Wen Yan", chinese: "大人者, 与天地合其德" },
        { text: "The way of the Creative works through change and transformation.", source: "I Ching, Xiang Zhuan", chinese: "天行健, 君子以自强不息" },
        { text: "The receptive accommodates everything, thus it is the vessel of the way.", source: "I Ching, Tuan Zhuan", chinese: "地势坤, 君子以厚德载物" },
        { text: "Before the beginning of great brilliance, there must be chaos.", source: "I Ching, Hexagram 3", chinese: "云雷屯, 君子以经纶" },
        { text: "When the way comes to an end, then there is change. With change there is solution.", source: "I Ching, Xici", chinese: "穷则变, 变则通" },
        { text: "The Book of Changes contains the measure of heaven and earth.", source: "I Ching, Xici", chinese: "易与天地准" },
        { text: "Heaven creates, earth nourishes, man completes.", source: "I Ching, Xici", chinese: "天地人, 三才之道" },
        { text: "The sage looks up to observe the phenomena of heaven and looks down to examine the patterns of earth.", source: "I Ching, Xici", chinese: "仰观天文, 俯察地理" },
        { text: "The Changes have no thought, no action. They are still and yet move all things.", source: "I Ching, Xici", chinese: "易无思也, 无为也" },
        { text: "That which is above form is called the Way; that which is within form is called the vessel.", source: "I Ching, Xici", chinese: "形而上者谓之道, 形而下者谓之器" },
        { text: "The great man is he who is in harmony with the attributes of heaven and earth.", source: "I Ching, Wen Yan", chinese: "夫大人者, 与天地合其德" },
        { text: "Water flows to the wet places, fire rises to the dry places.", source: "I Ching, Xici", chinese: "水流湿, 火就燥" },
        { text: "The way of heaven is to diminish the excessive and supplement the insufficient.", source: "I Ching, Hexagram 15", chinese: "天道亏盈而益谦" },
        { text: "To know the seeds, that is divine indeed.", source: "I Ching, Xici", chinese: "知几其神乎" },
        { text: "The sage uses the divine way for teaching, and the whole world submits.", source: "I Ching, Xici", chinese: "圣人以神道设教, 而天下服矣" },
        { text: "The yielding conquers the hard; the weak conquers the strong.", source: "Laozi, Dao De Jing 78", chinese: "柔弱胜刚强" },
        { text: "The highest good is like water. Water benefits all things and does not compete.", source: "Laozi, Dao De Jing 8", chinese: "上善若水, 水善利万物而不争" },
        { text: "The way that can be told is not the eternal way.", source: "Laozi, Dao De Jing 1", chinese: "道可道, 非常道" },
        { text: "Act without action; do without doing.", source: "Laozi, Dao De Jing 63", chinese: "为无为, 事无事" },
        { text: "Knowing others is wisdom; knowing yourself is enlightenment.", source: "Laozi, Dao De Jing 33", chinese: "知人者智, 自知者明" },
        { text: "The journey of a thousand miles begins with a single step.", source: "Laozi, Dao De Jing 64", chinese: "千里之行, 始于足下" },
        { text: "Those who know do not speak. Those who speak do not know.", source: "Laozi, Dao De Jing 56", chinese: "知者不言, 言者不知" },
        { text: "When I let go of what I am, I become what I might be.", source: "Laozi, Dao De Jing", chinese: "损之又损, 以至于无为" },
        { text: "Nature does not hurry, yet everything is accomplished.", source: "Laozi, Dao De Jing", chinese: "道法自然" },
        { text: "He who stands on tiptoe does not stand firm.", source: "Laozi, Dao De Jing 24", chinese: "企者不立" },
        { text: "Return is the motion of the Tao. Yielding is the way of the Tao.", source: "Laozi, Dao De Jing 40", chinese: "反者道之动, 弱者道之用" },
        { text: "The sage does not accumulate. The more he does for others, the more he has.", source: "Laozi, Dao De Jing 81", chinese: "圣人不积, 既以为人己愈有" },
        { text: "Be still like a mountain, flow like a great river.", source: "Laozi, Dao De Jing", chinese: "泰山不让土壤, 河海不择细流" },
        { text: "Without going outside, you may know the whole world.", source: "Laozi, Dao De Jing 47", chinese: "不出户, 知天下" },
        { text: "The sage manages affairs without action.", source: "Laozi, Dao De Jing 63", chinese: "圣人处无为之事" }
    ],
    zh: [
        { text: "大人者, 与天地合其德, 与日月合其明, 与四时合其序", source: "易经·文言传", chinese: "" },
        { text: "天行健, 君子以自强不息", source: "易经·象传", chinese: "" },
        { text: "地势坤, 君子以厚德载物", source: "易经·象传", chinese: "" },
        { text: "穷则变, 变则通, 通则久", source: "易经·系辞下", chinese: "" },
        { text: "一阴一阳之谓道", source: "易经·系辞上", chinese: "" },
        { text: "易与天地准, 故能弥纶天地之道", source: "易经·系辞上", chinese: "" },
        { text: "仰以观于天文, 俯以察于地理", source: "易经·系辞上", chinese: "" },
        { text: "形而上者谓之道, 形而下者谓之器", source: "易经·系辞上", chinese: "" },
        { text: "知几其神乎？君子上交不谄, 下交不渎", source: "易经·系辞下", chinese: "" },
        { text: "圣人以神道设教, 而天下服矣", source: "易经·观卦", chinese: "" },
        { text: "同声相应, 同气相求", source: "易经·乾卦", chinese: "" },
        { text: "水流湿, 火就燥", source: "易经·系辞上", chinese: "" },
        { text: "天道亏盈而益谦, 地道变盈而流谦", source: "易经·谦卦", chinese: "" },
        { text: "积善之家, 必有余庆; 积不善之家, 必有余殃", source: "易经·坤卦", chinese: "" },
        { text: "君子以恐惧修省", source: "易经·震卦", chinese: "" },
        { text: "上善若水。水善利万物而不争", source: "老子·道德经第八章", chinese: "" },
        { text: "道可道, 非常道; 名可名, 非常名", source: "老子·道德经第一章", chinese: "" },
        { text: "为学日益, 为道日损", source: "老子·道德经第四十八章", chinese: "" },
        { text: "知人者智, 自知者明", source: "老子·道德经第三十三章", chinese: "" },
        { text: "千里之行, 始于足下", source: "老子·道德经第六十四章", chinese: "" },
        { text: "大直若屈, 大巧若拙", source: "老子·道德经第四十五章", chinese: "" },
        { text: "反者道之动, 弱者道之用", source: "老子·道德经第四十章", chinese: "" },
        { text: "人法地, 地法天, 天法道, 道法自然", source: "老子·道德经第二十五章", chinese: "" },
        { text: "合抱之木, 生于毫末", source: "老子·道德经第六十四章", chinese: "" },
        { text: "道生一, 一生二, 二生三, 三生万物", source: "老子·道德经第四十二章", chinese: "" },
        { text: "致虚极, 守静笃", source: "老子·道德经第十六章", chinese: "" },
        { text: "无为而无不为", source: "老子·道德经第四十八章", chinese: "" },
        { text: "天下之至柔, 驰骋天下之至坚", source: "老子·道德经第四十三章", chinese: "" },
        { text: "见素抱朴, 少私寡欲", source: "老子·道德经第十九章", chinese: "" },
        { text: "生而不有, 为而不恃, 长而不宰", source: "老子·道德经第十章", chinese: "" }
    ],
    es: [
        { text: "El hombre superior comprende las señales del cielo y conoce las causas de los eventos.", source: "I Ching, Wen Yan", chinese: "大人者, 与天地合其德" },
        { text: "El camino de lo Creativo trabaja a través del cambio y la transformación.", source: "I Ching, Xiang Zhuan", chinese: "天行健, 君子以自强不息" },
        { text: "Lo Receptivo acomoda todo, así es el recipiente del camino.", source: "I Ching, Tuan Zhuan", chinese: "地势坤, 君子以厚德载物" },
        { text: "Antes del inicio de la gran brillantez, debe haber caos.", source: "I Ching, Hexagrama 3", chinese: "云雷屯" },
        { text: "Cuando el camino llega a su fin, entonces hay cambio. Con el cambio hay solución.", source: "I Ching, Xici", chinese: "穷则变, 变则通" },
        { text: "El Libro de los Cambios contiene la medida del cielo y la tierra.", source: "I Ching, Xici", chinese: "易与天地准" },
        { text: "El cielo crea, la tierra nutre, el hombre completa.", source: "I Ching, Xici", chinese: "天地人, 三才之道" },
        { text: "El sabio mira hacia arriba para observar los fenómenos del cielo y hacia abajo para examinar los patrones de la tierra.", source: "I Ching, Xici", chinese: "仰观天文, 俯察地理" },
        { text: "Los Cambios no tienen pensamiento, no tienen acción. Están quietos y sin embargo mueven todas las cosas.", source: "I Ching, Xici", chinese: "易无思也, 无为也" },
        { text: "Aquello que está por encima de la forma se llama el Camino; aquello que está dentro de la forma se llama el recipiente.", source: "I Ching, Xici", chinese: "形而上者谓之道" },
        { text: "El gran hombre es aquel que está en armonía con los atributos del cielo y la tierra.", source: "I Ching, Wen Yan", chinese: "夫大人者" },
        { text: "El agua fluye hacia los lugares húmedos, el fuego se eleva hacia los lugares secos.", source: "I Ching, Xici", chinese: "水流湿, 火就燥" },
        { text: "La manera del cielo es disminuir lo excesivo y suplementar lo insuficiente.", source: "I Ching, Hexagrama 15", chinese: "天道亏盈而益谦" },
        { text: "Conocer las semillas, eso es divino de verdad.", source: "I Ching, Xici", chinese: "知几其神乎" },
        { text: "El sabio usa el camino divino para enseñar, y todo el mundo se somete.", source: "I Ching, Xici", chinese: "圣人以神道设教" },
        { text: "Lo suave conquista lo duro; lo débil conquista lo fuerte.", source: "Laozi, Dao De Jing 78", chinese: "柔弱胜刚强" },
        { text: "El bien más alto es como el agua. El agua beneficia todas las cosas y no compite.", source: "Laozi, Dao De Jing 8", chinese: "上善若水" },
        { text: "El camino que puede ser dicho no es el camino eterno.", source: "Laozi, Dao De Jing 1", chinese: "道可道, 非常道" },
        { text: "Actúa sin acción; haz sin hacer.", source: "Laozi, Dao De Jing 63", chinese: "为无为" },
        { text: "Conocer a otros es sabiduría; conocerse a uno mismo es iluminación.", source: "Laozi, Dao De Jing 33", chinese: "知人者智, 自知者明" },
        { text: "El viaje de mil millas comienza con un solo paso.", source: "Laozi, Dao De Jing 64", chinese: "千里之行" },
        { text: "Aquellos que saben no hablan. Aquellos que hablan no saben.", source: "Laozi, Dao De Jing 56", chinese: "知者不言" },
        { text: "Cuando dejo ir lo que soy, me convierto en lo que podría ser.", source: "Laozi, Dao De Jing", chinese: "损之又损" },
        { text: "La naturaleza no se apresura, y sin embargo todo se logra.", source: "Laozi, Dao De Jing", chinese: "道法自然" },
        { text: "Aquel que se para de puntillas no se mantiene firme.", source: "Laozi, Dao De Jing 24", chinese: "企者不立" },
        { text: "El retorno es el movimiento del Tao. Cedencia es el camino del Tao.", source: "Laozi, Dao De Jing 40", chinese: "反者道之动" },
        { text: "El sabio no acumula. Cuanto más hace por otros, más tiene.", source: "Laozi, Dao De Jing 81", chinese: "圣人不积" },
        { text: "Estate quieto como una montaña, fluye como un gran río.", source: "Laozi, Dao De Jing", chinese: "泰山不让土壤" },
        { text: "Sin salir afuera, puedes conocer el mundo entero.", source: "Laozi, Dao De Jing 47", chinese: "不出户" },
        { text: "El sabio maneja asuntos sin acción.", source: "Laozi, Dao De Jing 63", chinese: "圣人处无为之事" }
    ],
    it: [
        { text: "L'uomo superiore comprende i segni del cielo e conosce le cause degli eventi.", source: "I Ching, Wen Yan", chinese: "大人者, 与天地合其德" },
        { text: "La via del Creativo opera attraverso il cambiamento e la trasformazione.", source: "I Ching, Xiang Zhuan", chinese: "天行健, 君子以自强不息" },
        { text: "Il Ricettivo accoglie tutto, quindi è il recipiente della via.", source: "I Ching, Tuan Zhuan", chinese: "地势坤, 君子以厚德载物" },
        { text: "Prima dell'inizio della grande brillantezza, ci deve essere il caos.", source: "I Ching, Esagramma 3", chinese: "云雷屯" },
        { text: "Quando la via giunge alla fine, allora c'è il cambiamento. Con il cambiamento c'è la soluzione.", source: "I Ching, Xici", chinese: "穷则变, 变则通" },
        { text: "Il Libro dei Mutamenti contiene la misura del cielo e della terra.", source: "I Ching, Xici", chinese: "易与天地准" },
        { text: "Il cielo crea, la terra nutre, l'uomo completa.", source: "I Ching, Xici", chinese: "天地人, 三才之道" },
        { text: "Il saggio guarda in alto per osservare i fenomeni del cielo e guarda in basso per esaminare i modelli della terra.", source: "I Ching, Xici", chinese: "仰观天文, 俯察地理" },
        { text: "I Mutamenti non hanno pensiero, non hanno azione. Sono fermi eppure muovono tutte le cose.", source: "I Ching, Xici", chinese: "易无思也, 无为也" },
        { text: "Ciò che è al di sopra della forma si chiama la Via; ciò che è entro la forma si chiama il recipiente.", source: "I Ching, Xici", chinese: "形而上者谓之道" },
        { text: "Il grande uomo è colui che è in armonia con gli attributi del cielo e della terra.", source: "I Ching, Wen Yan", chinese: "夫大人者" },
        { text: "L'acqua scorre verso i luoghi umidi, il fuoco sale verso i luoghi secchi.", source: "I Ching, Xici", chinese: "水流湿, 火就燥" },
        { text: "La via del cielo è diminuire l'eccessivo e supplementare l'insufficiente.", source: "I Ching, Esagramma 15", chinese: "天道亏盈而益谦" },
        { text: "Conoscere i semi, quello è divino davvero.", source: "I Ching, Xici", chinese: "知几其神乎" },
        { text: "Il saggio usa la via divina per insegnare, e il mondo intero si sottomette.", source: "I Ching, Xici", chinese: "圣人以神道设教" },
        { text: "Il cedevole conquista il duro; il debole conquista il forte.", source: "Laozi, Dao De Jing 78", chinese: "柔弱胜刚强" },
        { text: "Il bene più alto è come l'acqua. L'acqua beneficia tutte le cose e non compete.", source: "Laozi, Dao De Jing 8", chinese: "上善若水" },
        { text: "La via che può essere detta non è la via eterna.", source: "Laozi, Dao De Jing 1", chinese: "道可道, 非常道" },
        { text: "Agisci senza azione; fa' senza fare.", source: "Laozi, Dao De Jing 63", chinese: "为无为" },
        { text: "Conoscere gli altri è saggezza; conoscere te stesso è illuminazione.", source: "Laozi, Dao De Jing 33", chinese: "知人者智, 自知者明" },
        { text: "Il viaggio di mille miglia comincia con un singolo passo.", source: "Laozi, Dao De Jing 64", chinese: "千里之行" },
        { text: "Coloro che sanno non parlano. Coloro che parlano non sanno.", source: "Laozi, Dao De Jing 56", chinese: "知者不言" },
        { text: "Quando lascio andare ciò che sono, divento ciò che potrei essere.", source: "Laozi, Dao De Jing", chinese: "损之又损" },
        { text: "La natura non si affretta, eppure tutto si compie.", source: "Laozi, Dao De Jing", chinese: "道法自然" },
        { text: "Colui che sta in punta di piedi non sta saldo.", source: "Laozi, Dao De Jing 24", chinese: "企者不立" },
        { text: "Il ritorno è il movimento del Tao. La cedenza è la via del Tao.", source: "Laozi, Dao De Jing 40", chinese: "反者道之动" },
        { text: "Il saggio non accumula. Più fa per gli altri, più ha.", source: "Laozi, Dao De Jing 81", chinese: "圣人不积" },
        { text: "Stai fermo come una montagna, scorri come un grande fiume.", source: "Laozi, Dao De Jing", chinese: "泰山不让土壤" },
        { text: "Senza uscire fuori, puoi conoscere il mondo intero.", source: "Laozi, Dao De Jing 47", chinese: "不出户" },
        { text: "Il saggio gestisce gli affari senza azione.", source: "Laozi, Dao De Jing 63", chinese: "圣人处无为之事" }
    ]
};

// Debug/Process Messages
const PROCESS_MESSAGES = {
    en: [
        "Calculating hexagram configuration...",
        "Consulting the Book of Changes...",
        "Analyzing line transformations...",
        "Determining trigram relationships...",
        "Computing celestial positions...",
        "Analyzing lunar mansion influence...",
        "Calculating BaZi (Four Pillars)...",
        "Computing He Tu (River Map)...",
        "Calculating Luo Shu (Magic Square)...",
        "Analyzing Tai Sui position...",
        "Synchronizing with celestial time...",
        "Consulting classical texts...",
        "Generating wisdom interpretation...",
        "Composing celestial guidance...",
        "Analyzing Five Elements balance...",
        "Calculating remedy alignments...",
        "Finalizing astrological context...",
        "Synthesizing interpretation...",
        "Rendering complete analysis..."
    ],
    zh: [
        "计算卦象配置...",
        "查阅易经...",
        "分析爻变...",
        "确定卦象关系...",
        "计算天体位置...",
        "分析星宿影响...",
        "计算八字...",
        "计算河图...",
        "计算洛书...",
        "分析太岁位置...",
        "同步天体时间...",
        "查阅经典文本...",
        "生成智慧解读...",
        "撰写天体指引...",
        "分析五行平衡...",
        "计算补救对齐...",
        "完成占星背景...",
        "综合解读...",
        "渲染完整分析..."
    ],
    es: [
        "Calculando configuración del hexagrama...",
        "Consultando el Libro de los Cambios...",
        "Analizando transformaciones de líneas...",
        "Determinando relaciones de trigramas...",
        "Computando posiciones celestiales...",
        "Analizando influencia de la mansión lunar...",
        "Calculando BaZi (Cuatro Pilares)...",
        "Computando He Tu (Mapa del Río)...",
        "Calculando Luo Shu (Cuadrado Mágico)...",
        "Analizando posición del Tai Sui...",
        "Sincronizando con tiempo celestial...",
        "Consultando textos clásicos...",
        "Generando interpretación de sabiduría...",
        "Componiendo guía celestial...",
        "Analizando balance de Cinco Elementos...",
        "Calculando alineaciones de remedios...",
        "Finalizando contexto astrológico...",
        "Sintetizando interpretación...",
        "Renderizando análisis completo..."
    ],
    it: [
        "Calcolando configurazione dell'esagramma...",
        "Consultando il Libro dei Mutamenti...",
        "Analizzando trasformazioni delle linee...",
        "Determinando relazioni dei trigrammi...",
        "Calcolando posizioni celestiali...",
        "Analizzando influenza della mansione lunare...",
        "Calcolando BaZi (Quattro Pilastri)...",
        "Calcolando He Tu (Mappa del Fiume)...",
        "Calcolando Luo Shu (Quadrato Magico)...",
        "Analizzando posizione del Tai Sui...",
        "Sincronizzando con tempo celestiale...",
        "Consultando testi classici...",
        "Generando interpretazione della saggezza...",
        "Componendo guida celestiale...",
        "Analizzando bilancia dei Cinque Elementi...",
        "Calcolando allineamenti dei rimedi...",
        "Finalizzando contesto astrologico...",
        "Sintetizzando interpretazione...",
        "Renderizzando analisi completa..."
    ]
};

// Get random quote for loading screen
function getRandomQuote(lang) {
    const quotes = YIJING_QUOTES[lang] || YIJING_QUOTES['en'];
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

// Get process message by index
function getProcessMessage(lang, index) {
    const messages = PROCESS_MESSAGES[lang] || PROCESS_MESSAGES['en'];
    return messages[index % messages.length];
}
